version: "3.8"

services:
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/loki
      - ./loki-config.yml:/etc/loki/local-config.yaml
    networks:
      - jupiter-network
    restart: unless-stopped

  jupiter-swap-api:
    build: .
    env_file:
      - jupiter-config.env
    ports:
      - "${API_PORT:-8080}:8080"
    environment:
      - RUST_LOG=${RUST_LOG:-info}
    command: >
      sh -c "
      ./jupiter-swap-api
      --rpc-url $${RPC_URL}
      -e $${YELLOWSTONE_GRPC_URL}
      -x $${YELLOWSTONE_GRPC_ACCESS_KEY}
      $${YELLOWSTONE_GRPC_ENABLE_PING:+--yellowstone-grpc-enable-ping}
      $${ALLOW_CIRCULAR_ARBITRAGE:+--allow-circular-arbitrage}
      --total-thread-count $${TOTAL_THREAD_COUNT:-64}
      "
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - jupiter-network
    restart: unless-stopped
    depends_on:
      - loki

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - jupiter-network
    restart: unless-stopped
    depends_on:
      - loki

volumes:
  loki-data:

networks:
  jupiter-network:
    driver: bridge
